
spring:
  cloud:
    nacos:
      #username
      #      username: nacos
      #password
      #      password: nacos
      discovery:
        #集群名称
        cluster-name: HK
        #id:端口号
        server-addr: 192.168.0.5:8848
        #命名空间
        namespace: 03a5daf8-55c4-45af-bb8b-59bb49ef2fe0

